### PR TITLE
is_reminders_set confusing

### PR DESCRIPTION
**Pull request by Doc999tor**

### CODE REVIEW

**Comment by Doc999tor** [comment]
@tkachuks pls check if it's still relevant

**Comment by Doc999tor** [comment]
@tkachuks Did you checked this fix? It seems like probably no need / non relevant

**Comment by tkachuks** [comment]
all pull requests from myershov not relevant

**Comment by Doc999tor** [comment]
Why did you merged it? 
Pls make some cleanings in the repo - delete all the non-relevant stuff

**Pull request merged**
